Illumina sample sheet v1 pairing
mll-lab/php-utils pull request #23
Opened 2024-06-13 09:42 UTC by fischerl

- [ ] Added automated tests
- [ ] Documented for all relevant versions
- [ ] Updated the changelog

**Changes**

**Breaking changes**

2024-06-13 13:48 UTC, fischerl commented on tests/IlluminaSampleSheet/V1/DualIndexWithLaneTest.php
> +        // TODO how to enfore that this type is written
@spawnia Hast du eine Idee wie wir erzwingen koennen dass dieser Typ `DataSection<RowForDualIndexWithLane>` immer angegeben werden muss?

2024-06-14 07:44 UTC, fischerl commented on src/IlluminaSampleSheet/V2/NovaSeqXSampleSheet.php
> +class NovaSeqXSampleSheet extends BaseSampleSheet
@simbig Wollen wir das Naming der Klasse vielleicht noch anpassen? Also Eher NovaSeqV1SampleSheet?

2024-06-14 09:45 UTC, simbig commented on src/IlluminaSampleSheet/V2/NovaSeqXSampleSheet.php
> +class NovaSeqXSampleSheet extends BaseSampleSheet
Analog zu dem neuen Wäre es ja dann "V1/SampleSheet". Kannst du gerne machen. Entsprechenden Breaking change im changelog eintragen

2024-06-14 10:11 UTC, simbig requested changes

2024-06-14 10:11 UTC, simbig commented on src/IlluminaSampleSheet/V1/Row.php
> +    abstract public function getColumns(): Collection;
```suggestion
    abstract public function headerLine(): string;
```
This should simplify it a bit and we do not have any need for structured informations about the header with this implementation, right?

2024-06-14 10:11 UTC, simbig commented on tests/IlluminaSampleSheet/V1/DualIndexWithoutLaneTest.php
> +    }
Please extract these tests to a DataSectionTest.php file.

2024-06-14 10:11 UTC, simbig commented on tests/IlluminaSampleSheet/V1/DualIndexWithLaneTest.php
> +    }
Please extract this test to a DataSectionTest.php file.

2024-06-17 07:18 UTC, simbig commented
please do not forget to update the changelog

2024-06-17 07:25 UTC, simbig approved these changes

2024-06-17 07:26 UTC, merged